const test_cases = [
// --- Problem 21: Factorial ---
{ problem_id: 21, input: "5", expected_output: "120", is_sample: true },
{ problem_id: 21, input: "0", expected_output: "1", is_sample: false },
{ problem_id: 21, input: "1", expected_output: "1", is_sample: false },
{ problem_id: 21, input: "10", expected_output: "3628800", is_sample: false },
{ problem_id: 21, input: "15", expected_output: "1307674368000", is_sample: false },
{ problem_id: 21, input: "20", expected_output: "2432902008176640000", is_sample: false },
{ problem_id: 21, input: "3", expected_output: "6", is_sample: false },
{ problem_id: 21, input: "7", expected_output: "5040", is_sample: false },
{ problem_id: 21, input: "12", expected_output: "479001600", is_sample: false },
{ problem_id: 21, input: "18", expected_output: "6402373705728000", is_sample: false },
{ problem_id: 21, input: "4", expected_output: "24", is_sample: false },
{ problem_id: 21, input: "2", expected_output: "2", is_sample: false },
{ problem_id: 21, input: "6", expected_output: "720", is_sample: false },
{ problem_id: 21, input: "9", expected_output: "362880", is_sample: false },
{ problem_id: 21, input: "8", expected_output: "40320", is_sample: false },

// --- Problem 22: Fibonacci Numbers ---
{ problem_id: 22, input: "10", expected_output: "55", is_sample: true },
{ problem_id: 22, input: "0", expected_output: "0", is_sample: false },
{ problem_id: 22, input: "1", expected_output: "1", is_sample: false },
{ problem_id: 22, input: "20", expected_output: "6765", is_sample: false },
{ problem_id: 22, input: "30", expected_output: "832040", is_sample: false },
{ problem_id: 22, input: "40", expected_output: "102334155", is_sample: false },
{ problem_id: 22, input: "5", expected_output: "5", is_sample: false },
{ problem_id: 22, input: "15", expected_output: "610", is_sample: false },
{ problem_id: 22, input: "25", expected_output: "75025", is_sample: false },
{ problem_id: 22, input: "35", expected_output: "9227465", is_sample: false },
{ problem_id: 22, input: "12", expected_output: "144", is_sample: false },
{ problem_id: 22, input: "2", expected_output: "1", is_sample: false },
{ problem_id: 22, input: "3", expected_output: "2", is_sample: false },
{ problem_id: 22, input: "4", expected_output: "3", is_sample: false },
{ problem_id: 22, input: "6", expected_output: "8", is_sample: false },

// --- Problem 23: Permutations ---
{ problem_id: 23, input: "3", expected_output: "1 2 3\n1 3 2\n2 1 3\n2 3 1\n3 1 2\n3 2 1", is_sample: true },
{ problem_id: 23, input: "1", expected_output: "1", is_sample: false },
{ problem_id: 23, input: "2", expected_output: "1 2\n2 1", is_sample: false },
{ problem_id: 23, input: "4", expected_output: "", is_sample: false },
{ problem_id: 23, input: "5", expected_output: "", is_sample: false },
{ problem_id: 23, input: "6", expected_output: "", is_sample: false },
{ problem_id: 23, input: "7", expected_output: "", is_sample: false },
{ problem_id: 23, input: "8", expected_output: "", is_sample: false },
{ problem_id: 23, input: "9", expected_output: "", is_sample: false },
{ problem_id: 23, input: "10", expected_output: "", is_sample: false },
{ problem_id: 23, input: "3", expected_output: "1 2 3\n1 3 2\n2 1 3\n2 3 1\n3 1 2\n3 2 1", is_sample: false },
{ problem_id: 23, input: "1", expected_output: "1", is_sample: false },
{ problem_id: 23, input: "2", expected_output: "1 2\n2 1", is_sample: false },
{ problem_id: 23, input: "5", expected_output: "", is_sample: false },
{ problem_id: 23, input: "4", expected_output: "", is_sample: false },

// --- Problem 24: Sum of Digits ---
{ problem_id: 24, input: "1234", expected_output: "10", is_sample: true },
{ problem_id: 24, input: "0", expected_output: "0", is_sample: false },
{ problem_id: 24, input: "9", expected_output: "9", is_sample: false },
{ problem_id: 24, input: "10", expected_output: "1", is_sample: false },
{ problem_id: 24, input: "1111", expected_output: "4", is_sample: false },
{ problem_id: 24, input: "999999999", expected_output: "81", is_sample: false },
{ problem_id: 24, input: "1000000000", expected_output: "1", is_sample: false },
{ problem_id: 24, input: "987654321", expected_output: "45", is_sample: false },
{ problem_id: 24, input: "456", expected_output: "15", is_sample: false },
{ problem_id: 24, input: "55555", expected_output: "25", is_sample: false },
{ problem_id: 24, input: "123456789", expected_output: "45", is_sample: false },
{ problem_id: 24, input: "2222", expected_output: "8", is_sample: false },
{ problem_id: 24, input: "7777", expected_output: "28", is_sample: false },
{ problem_id: 24, input: "121212", expected_output: "9", is_sample: false },
{ problem_id: 24, input: "33333", expected_output: "15", is_sample: false },

// --- Problem 25: Tower of Hanoi ---
{ problem_id: 25, input: "2", expected_output: "Move disk from 1 to 2\nMove disk from 1 to 3\nMove disk from 2 to 3", is_sample: true },
{ problem_id: 25, input: "1", expected_output: "Move disk from 1 to 3", is_sample: false },
{ problem_id: 25, input: "3", expected_output: "", is_sample: false },
{ problem_id: 25, input: "4", expected_output: "", is_sample: false },
{ problem_id: 25, input: "5", expected_output: "", is_sample: false },
{ problem_id: 25, input: "6", expected_output: "", is_sample: false },
{ problem_id: 25, input: "7", expected_output: "", is_sample: false },
{ problem_id: 25, input: "8", expected_output: "", is_sample: false },
{ problem_id: 25, input: "9", expected_output: "", is_sample: false },
{ problem_id: 25, input: "10", expected_output: "", is_sample: false },
{ problem_id: 25, input: "1", expected_output: "Move disk from 1 to 3", is_sample: false },
{ problem_id: 25, input: "2", expected_output: "Move disk from 1 to 2\nMove disk from 1 to 3\nMove disk from 2 to 3", is_sample: false },
{ problem_id: 25, input: "3", expected_output: "", is_sample: false },
{ problem_id: 25, input: "4", expected_output: "", is_sample: false },
{ problem_id: 25, input: "5", expected_output: "", is_sample: false },

// --- Problem 26: Sum of Array Elements ---
{ problem_id: 26, input: "5\n1 2 3 4 5", expected_output: "15", is_sample: true },
{ problem_id: 26, input: "3\n-1 2 -3", expected_output: "-2", is_sample: false },
{ problem_id: 26, input: "4\n0 0 0 0", expected_output: "0", is_sample: false },
{ problem_id: 26, input: "1\n100", expected_output: "100", is_sample: false },
{ problem_id: 26, input: "2\n-100 100", expected_output: "0", is_sample: false },
{ problem_id: 26, input: "6\n1 1 1 1 1 1", expected_output: "6", is_sample: false },
{ problem_id: 26, input: "4\n1000000000 -1000000000 1000000000 -1000000000", expected_output: "0", is_sample: false },
{ problem_id: 26, input: "5\n2 4 6 8 10", expected_output: "30", is_sample: false },
{ problem_id: 26, input: "3\n-10 -20 -30", expected_output: "-60", is_sample: false },
{ problem_id: 26, input: "7\n7 7 7 7 7 7 7", expected_output: "49", is_sample: false },
{ problem_id: 26, input: "2\n2147483647 2147483647", expected_output: "4294967294", is_sample: false },
{ problem_id: 26, input: "3\n-2147483648 -1 -1", expected_output: "-2147483648", is_sample: false },
{ problem_id: 26, input: "4\n1 3 5 7", expected_output: "16", is_sample: false },
{ problem_id: 26, input: "5\n10 20 30 40 50", expected_output: "150", is_sample: false },
{ problem_id: 26, input: "3\n0 0 0", expected_output: "0", is_sample: false },

// --- Problem 27: Count Paths in Grid ---
{ problem_id: 27, input: "2 2", expected_output: "2", is_sample: true },
{ problem_id: 27, input: "1 1", expected_output: "1", is_sample: false },
{ problem_id: 27, input: "3 3", expected_output: "6", is_sample: false },
{ problem_id: 27, input: "4 4", expected_output: "20", is_sample: false },
{ problem_id: 27, input: "5 5", expected_output: "70", is_sample: false },
{ problem_id: 27, input: "10 10", expected_output: "48620", is_sample: false },
{ problem_id: 27, input: "20 20", expected_output: "137846528820", is_sample: false },
{ problem_id: 27, input: "15 15", expected_output: "40116600", is_sample: false },
{ problem_id: 27, input: "2 10", expected_output: "11", is_sample: false },
{ problem_id: 27, input: "10 2", expected_output: "11", is_sample: false },
{ problem_id: 27, input: "12 12", expected_output: "2496144", is_sample: false },
{ problem_id: 27, input: "3 7", expected_output: "28", is_sample: false },
{ problem_id: 27, input: "7 3", expected_output: "28", is_sample: false },
{ problem_id: 27, input: "6 5", expected_output: "126", is_sample: false },
{ problem_id: 27, input: "5 6", expected_output: "126", is_sample: false },

// --- Problem 28: Palindrome Check ---
{ problem_id: 28, input: "racecar", expected_output: "YES", is_sample: true },
{ problem_id: 28, input: "hello", expected_output: "NO", is_sample: false },
{ problem_id: 28, input: "aaa", expected_output: "YES", is_sample: false },
{ problem_id: 28, input: "abcba", expected_output: "YES", is_sample: false },
{ problem_id: 28, input: "abccba", expected_output: "YES", is_sample: false },
{ problem_id: 28, input: "abcdba", expected_output: "NO", is_sample: false },
{ problem_id: 28, input: "a", expected_output: "YES", is_sample: false },
{ problem_id: 28, input: "ab", expected_output: "NO", is_sample: false },
{ problem_id: 28, input: "aba", expected_output: "YES", is_sample: false },
{ problem_id: 28, input: "abc", expected_output: "NO", is_sample: false },
{ problem_id: 28, input: "abba", expected_output: "YES", is_sample: false },
{ problem_id: 28, input: "xyzzyx", expected_output: "YES", is_sample: false },
{ problem_id: 28, input: "xyzzyw", expected_output: "NO", is_sample: false },
{ problem_id: 28, input: "aabbccddccbbaa", expected_output: "YES", is_sample: false },
{ problem_id: 28, input: "aabbccddccbaaa", expected_output: "NO", is_sample: false },

// --- Problem 29: Expression Evaluation ---
{ problem_id: 29, input: "(1+(2*3))", expected_output: "7", is_sample: true },
{ problem_id: 29, input: "((2+3)*(4-1))", expected_output: "15", is_sample: false },
{ problem_id: 29, input: "(10+(20*30))", expected_output: "610", is_sample: false },
{ problem_id: 29, input: "(1+(2+(3+(4+5))))", expected_output: "15", is_sample: false },
{ problem_id: 29, input: "( ((1+2)+(3+4))*(5-6) )", expected_output: "-10", is_sample: false },
{ problem_id: 29, input: "((((1))))", expected_output: "1", is_sample: false },
{ problem_id: 29, input: "(2*(3+(4*5)))", expected_output: "46", is_sample: false },
{ problem_id: 29, input: "(1+(1+(1*(1+1))))", expected_output: "3", is_sample: false },
{ problem_id: 29, input: "(100+((200*3)-(100+50)))", expected_output: "550", is_sample: false },
{ problem_id: 29, input: "(1+2*3)", expected_output: "7", is_sample: false },
{ problem_id: 29, input: "((1+2)*(3+4))", expected_output: "21", is_sample: false },
{ problem_id: 29, input: "(5*(6+(7*8)))", expected_output: "310", is_sample: false },
{ problem_id: 29, input: "((1+1)+(1+1))", expected_output: "4", is_sample: false },
{ problem_id: 29, input: "((2+3)*(2+(3*4)))", expected_output: "70", is_sample: false },
{ problem_id: 29, input: "((10+20)*(30-5))", expected_output: "750", is_sample: false }
];

module.exports = { test_cases };
